package com.treyzania.gigalog;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.Instant;
import java.util.List;

public class Giga {

	public static final String LOG_PREFIX = "# Manifest generated by GigaLog (github.com/treyzania/GigaLog)\n";
	
	public static void main(String[] args) {
		
		// TODO Main sequence.
		
	}
	
	public static void writeLines(File outFile, List<Line> lines) {
		
		System.out.println("Writing manifest.");
		
		StringBuilder sb = new StringBuilder(LOG_PREFIX);
		sb.append("# Generated on " + Instant.now().toString());
		
		// Put all the lines here.
		for (Line line : lines) sb.append("\n" + line.toString());
		
		if (!outFile.exists()) {
			
			try {
				
				outFile.createNewFile();
				outFile.getParentFile().mkdirs();
				
			} catch (IOException ioe) {
				ioe.printStackTrace();
				System.exit(-1);
			}
			
		}
		
		try {
			
			FileOutputStream fos = new FileOutputStream(outFile);
			
			fos.write(sb.toString().getBytes());
			fos.flush();
			fos.close();
			
		} catch (IOException ioe) {
			ioe.printStackTrace();
		}
		
		System.out.println("Done writing manifest!");
		
	}
	
}
